/* eslint-disable */
// Generated by Wrangler by running `wrangler types cloudflare-env.d.ts --include-runtime=false` (hash: 8b355a9814db3fa7c9bf8eb0a7d59e47)
interface __BaseEnv_Env {
	SKY_CLIENT_LIMIT: RateLimit;
	SKY_LOCATION_LIMIT: RateLimit;
	AIRLABS_API_KEY: string;
	AIRLABS_BUDGET: DurableObjectNamespace<import("./worker").AirLabsBudget>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "AirLabsBudget";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AIRLABS_API_KEY">> {}
}
